CREATE CONSTRAINT tool_id IF NOT EXISTS FOR (t:Tool) REQUIRE t.id IS UNIQUE;
CREATE CONSTRAINT session_id IF NOT EXISTS FOR (s:Session) REQUIRE s.id IS UNIQUE;
CREATE CONSTRAINT checkpoint_key IF NOT EXISTS FOR (c:Checkpoint) REQUIRE (c.session_id, c.seq) IS UNIQUE;
CREATE CONSTRAINT registry_path IF NOT EXISTS FOR (r:RegistrySnapshot) REQUIRE r.path IS UNIQUE;
CREATE CONSTRAINT compaction_action_id IF NOT EXISTS FOR (a:CompactionAction) REQUIRE a.id IS UNIQUE;
CREATE CONSTRAINT compaction_policy_axis IF NOT EXISTS FOR (p:CompactionPolicy) REQUIRE p.axis IS UNIQUE;
CREATE CONSTRAINT prospect_id IF NOT EXISTS FOR (p:Prospect) REQUIRE p.id IS UNIQUE;
CREATE CONSTRAINT evidence_anchor IF NOT EXISTS FOR (e:Evidence) REQUIRE e.anchor IS UNIQUE;
CREATE INDEX tool_type IF NOT EXISTS FOR (t:Tool) ON (t.type);
CREATE INDEX compaction_op IF NOT EXISTS FOR (a:CompactionAction) ON (a.op);
CREATE FULLTEXT INDEX toolSearch IF NOT EXISTS FOR (t:Tool) ON EACH [t.name, t.description, t.target, t.type, t.id];
